#!/usr/bin/env python3
"""
Export user data from the HF DuckDB into SQL that D1 (wrangler) can
replay. Run this once per environment.

Usage
-----
  # 1. Download the live DuckDB from HF (or use a local copy)
  python migrate_from_duckdb.py \\
      --duckdb /path/to/masstamilan.duckdb \\
      --out    user_data.sql

  # 2. Apply to your D1 database
  wrangler d1 execute isaibox --remote --file=cloudflare/d1/schema/0001_init.sql
  wrangler d1 execute isaibox --remote --file=user_data.sql

The script intentionally only exports the user-related tables. The
catalog (songs, albums, scrape_runs) stays on HF for Phase 1.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

try:
    import duckdb  # type: ignore
except ImportError:
    print("duckdb is required: pip install duckdb", file=sys.stderr)
    raise SystemExit(1)


TABLES_USER = [
    "users",
    "user_sessions",
    "user_preferences",
    "favorite_songs",
    "favorite_albums",
    "favorite_album_entities",
    "favorite_music_directors",
    "playlists",
    "playlist_songs",
]

# Map DuckDB column → SQLite column for tables where types changed.
# Bool/TIMESTAMPTZ are converted in code below; this map only handles
# rename cases (none right now, but keeps the door open).
RENAMES: dict[str, dict[str, str]] = {}

# Columns expected per table in D1 (in INSERT order).
D1_COLUMNS: dict[str, list[str]] = {
    "users": [
        "user_id",
        "google_sub",
        "email",
        "name",
        "picture",
        "is_admin",
        "is_banned",
        "ban_reason",
        "last_login_at",
        "created_at",
        "updated_at",
    ],
    "user_sessions": ["session_id", "user_id", "expires_at", "created_at"],
    "user_preferences": [
        "user_id",
        "theme_preference",
        "main_tab",
        "recent_song_ids",
        "player_volume",
        "player_muted",
        "playback_speed",
        "repeat_mode",
        "autoplay_next",
        "updated_at",
    ],
    "favorite_songs": ["user_id", "song_id", "created_at"],
    "favorite_albums": ["user_id", "album_name", "created_at"],
    "favorite_album_entities": ["user_id", "album_url", "album_name", "created_at"],
    "favorite_music_directors": ["user_id", "music_director", "created_at"],
    "playlists": [
        "playlist_id",
        "user_id",
        "name",
        "is_global",
        "source",
        "source_url",
        "created_at",
        "updated_at",
    ],
    "playlist_songs": ["playlist_id", "song_id", "position", "added_at"],
}


def to_epoch(value: Any) -> int | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return int(value.timestamp())
    if isinstance(value, (int, float)):
        return int(value)
    if isinstance(value, str):
        try:
            return int(datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp())
        except ValueError:
            return None
    return None


def quote(value: Any, column: str) -> str:
    if value is None:
        return "NULL"
    if column.endswith("_at"):
        epoch = to_epoch(value)
        return "NULL" if epoch is None else str(epoch)
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return repr(value)
    s = str(value).replace("'", "''")
    return f"'{s}'"


def rows_to_inserts(table: str, rows: Iterable[tuple], columns: list[str]) -> Iterable[str]:
    column_list = ", ".join(columns)
    for row in rows:
        values = ", ".join(quote(v, c) for v, c in zip(row, columns))
        yield f"INSERT OR IGNORE INTO {table} ({column_list}) VALUES ({values});"


def main() -> None:
    ap = argparse.ArgumentParser(description="Export user data from DuckDB to D1-compatible SQL.")
    ap.add_argument("--duckdb", required=True, type=Path, help="Path to masstamilan.duckdb")
    ap.add_argument("--out", required=True, type=Path, help="Output SQL file")
    args = ap.parse_args()

    if not args.duckdb.exists():
        print(f"DuckDB file not found: {args.duckdb}", file=sys.stderr)
        raise SystemExit(2)

    conn = duckdb.connect(str(args.duckdb), read_only=True)
    total = 0
    with args.out.open("w", encoding="utf-8") as f:
        f.write("-- Generated by migrate_from_duckdb.py — do not edit by hand.\n")
        f.write("PRAGMA foreign_keys = OFF;\n")
        f.write("BEGIN TRANSACTION;\n\n")
        for table in TABLES_USER:
            columns = D1_COLUMNS[table]
            duckdb_cols = [RENAMES.get(table, {}).get(c, c) for c in columns]
            try:
                rows = conn.execute(
                    f"SELECT {', '.join(duckdb_cols)} FROM {table}"
                ).fetchall()
            except duckdb.Error as exc:
                print(f"Skipping {table}: {exc}", file=sys.stderr)
                continue
            f.write(f"-- {table} ({len(rows)} rows)\n")
            for line in rows_to_inserts(table, rows, columns):
                f.write(line + "\n")
            f.write("\n")
            total += len(rows)
        f.write("COMMIT;\n")
        f.write("PRAGMA foreign_keys = ON;\n")
    print(f"Wrote {total} rows to {args.out}")


if __name__ == "__main__":
    main()
